# .github/workflows/cleanup-images.yml
name: Cleanup Container Images

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at midnight on the first day of every month
  workflow_dispatch:  # Allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old images
        uses: snok/container-retention-policy@v2
        with:
          image-names: python-scripts
          cut-off: 2 weeks ago UTC
          account-type: personal
          keep-at-least: 5
          skip-tags: latest
          token: ${{ secrets.GITHUB_TOKEN }}